### ISSUE TITLE
I am not able to change the logo of the extension.

### ISSUE THREAD

**Issue by vignesh1507** [vignesh1507/Curse_Cloak#1]
There's a default 'c' symbol logo in the extension, i want to change that and i am not able to do that. Can anyone guide/help me with it?

**Comment by KartikMouli** [comment]
@vignesh1507 i would like to work on it. can us assign it to me ? under hacktoberfest label.

**Comment by KartikMouli** [comment]
@vignesh1507 i have created a pull request.please review :)
