### ISSUE TITLE
Toggle button to turn on or off  Curse_Cloak

### ISSUE THREAD

**Issue by KartikMouli** [vignesh1507/Curse_Cloak#2]
A toggle button that will turn on or off the usage of extension on chrome

**Comment by KartikMouli** [comment]
@vignesh1507 i would like to work on it.
can u add the hactoberfest label.

**Comment by vignesh1507** [comment]
Added it @KartikMouli, looking forward to work with you. Appreciate the initiative 🙌🏾

**Comment by jiyabansal123** [comment]
i am new in open source but want to work on this, as i see all issues are resolved to an extent is there anything i can do.

**Comment by vignesh1507** [comment]
You can go through the whole repository once and if you find any error or bug in any code file then you can rectify it, or you can go through other projects of mine by visiting my profile.

**Comment by TrueCoderSja** [comment]
I am working on the issue. Please assign the issue to me.
