### ISSUE TITLE
Suggestion : using 'badwords' or 'washyourmouthoutwithsoap' library

### ISSUE THREAD

**Issue by KartikMouli** [vignesh1507/Curse_Cloak#5]
using 'badwords' or 'washyourmouthoutwithsoap' module instead of custom cusswords.csv to filter the cusswords.
these libraries contains most of the badwords and supports multiple languages.

**Comment by vignesh1507** [comment]
We can use whichever module/library suits with our code. Lets make a new branch and make the changes in that, does that sound good?

**Comment by KartikMouli** [comment]
sure !

**Comment by vignesh1507** [comment]
created a new branch: version 0.1 we can work there.

**Comment by KartikMouli** [comment]
@vignesh1507 please add hacktoberfest label. ty !

**Comment by KartikMouli** [comment]
@vignesh1507 created pull request 👍
